name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: git describe --always --tags
      - run: npm install
      - run: npm list -g --depth=0
      - run: cd src && tar -czf ../bundle.debug *
      - run: cd .github && tar -czf ../bundle *
      - name: Archive bundles
        uses: actions/upload-artifact@v2
        with:
          name: bundles
          retention-days: 2
          path: |
            bundle
            bundle.debug
      - run: find . -ls

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: 'changelog-release.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: bundles
          path: .

      - run: find . -ls

      - name: Release
        uses: softprops/action-gh-release@v1
        id: Release
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          files: |
            README.md
            package.json
            bundle
            bundle.debug
