name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      - name: Install dependencies
        run: |
          npm install

  build:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - run: echo "build done" > result

  release:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: 'changelog-release.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        id: Release
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          files: |
            README.md
            package.json
            result
